# Generated by Django 3.2.6 on 2021-08-26 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_Price', models.CharField(max_length=10)),
                ('custname', models.CharField(max_length=50)),
                ('custemail', models.CharField(max_length=50)),
                ('custnumber', models.CharField(max_length=12)),
                ('custaddress', models.CharField(max_length=100)),
                ('order_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
