# Generated by Django 3.2.6 on 2021-08-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210827_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_Time',
            field=models.DateTimeField(auto_now=True, max_length=20),
        ),
    ]
