# Generated by Django 3.2.6 on 2021-08-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_update_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='statustext',
            field=models.CharField(choices=[('Order Received', 'Your Order is Received'), ('In Transit', 'Your Order is In Transit'), ('Out for Delivery', 'Your Order is Out for Delivery'), ('Order Delivered', 'Your Order is Delivered')], default='Order Received', max_length=50),
        ),
        migrations.AlterField(
            model_name='update',
            name='status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Order Delivered', 'Order Delivered')], default='Order Received', max_length=50),
        ),
    ]
