# Generated by Django 3.2.6 on 2021-08-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210827_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='statustext',
            field=models.CharField(choices=[('Your Order is Received', 'Order Received'), ('Your Order is In Transit', 'In Transit'), ('Your Order is Out for Delivery', 'Out for Delivery'), ('Your Order is Delivered', 'Order Delivered')], default='Order Received', max_length=50),
        ),
    ]
