# Generated by Django 3.2.6 on 2021-09-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_update_statustext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='status',
            field=models.CharField(choices=[('rder_received', 'Order Received'), ('In_transit', 'In Transit'), ('Out_for_delivery', 'Out for Delivery'), ('Order_delivered', 'Order Delivered')], default='Order Received', max_length=50),
        ),
        migrations.AlterField(
            model_name='update',
            name='statustext',
            field=models.CharField(choices=[('Your Order is Received', 'Your Order is Received'), ('Your Order is In Transit', 'Your Order is In Transit'), ('Your Order is Out for Delivery', 'Your Order is Out for Delivery'), ('Your Order is Delivered', 'Your Order is Delivered')], default='Your Order is Received', max_length=50),
        ),
    ]
